// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gduxpmhyhfueckgpimfi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdkdXhwbWh5aGZ1ZWNrZ3BpbWZpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkwNDc3MTMsImV4cCI6MjA2NDYyMzcxM30.9ReboVN5l4GRbwjp20y7UG8AE5NzRgnuKP5eTtjtMvs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);